- docs/releases/.gitignore
- docs/releases/secret.yml.tmp
- docs/releases/v0.0.1.yml
Add in some base yml files along with documentation to get started with the CCM
#10
> Documenation + yml

- Makefile
> basic makefile

- docs/releases/v0.0.2.yml
This release has instances, zones, and loadbalancers all implemented in the CCM
> Release yaml for v0.0.2

- README.md
- docs/ccm.md
- docs/examples/README.md
- docs/examples/cloud-controller-manager.yml
- docs/examples/load-balancer-https.yml
- docs/load-balancers.md
Fleshing out docs and examples
> updating docs + examples

- docs/releases/latest.yml
> adding latest yaml

- Makefile
- vultr/cloud.go
- vultr/fakeclient.go
- vultr/instances_test.go
- vultr/loadbalancer_test.go
- vultr/zones.go
- vultr/zones_test.go
> Unit Tests

- go.mod
- go.sum
- vendor/github.com/hashicorp/go-retryablehttp/README.md
- vendor/github.com/hashicorp/go-retryablehttp/client.go
- vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
- vendor/github.com/vultr/govultr/.travis.yml
- vendor/github.com/vultr/govultr/CHANGELOG.md
- vendor/github.com/vultr/govultr/block_storage.go
- vendor/github.com/vultr/govultr/go.mod
- vendor/github.com/vultr/govultr/go.sum
- vendor/github.com/vultr/govultr/govultr.go
- vendor/github.com/vultr/govultr/load_balancer.go
- vendor/github.com/vultr/govultr/object_storage.go
- vendor/modules.txt
- vultr/fakeclient.go
- vultr/loadbalancers.go
Bumped GoVultr to v0.4.0 which fixes the bug with not properly setting the `balancing_algorithm`. It also allows for attaching instances during LB creation which cuts back on some code.
> LB create + balancing_algo changes

- docs/releases/secret.yml.tmp
- docs/releases/v0.0.3.yml
With v0.0.3 we are changing the RBAC to limit what the CCM service account has access to.
> RBAC changes

- CHANGELOG.md
- docs/releases/latest.yml
Release for v0.0.3
#25 #24 #21 #23
> release for v0.0.3

- .github/workflows/tagged-releases.yml
Github action to publish the docker image on tagged releases.
n/a
> GH for releases

- go.mod
- go.sum
- vendor/github.com/vultr/metadata/CHANGELOG.md
- vendor/github.com/vultr/metadata/client.go
- vendor/github.com/vultr/metadata/go.mod
- vendor/github.com/vultr/metadata/metadata_json.go
- vendor/modules.txt
Updating the metadata client to support the new changes.
> updated metadata to supportnew changes

- .github/workflows/tagged-releases.yml
Update the go build version to match the go.mod version
> Bumping goversion on release

- docs/releases/latest.yml
- docs/releases/v0.1.2.yml
Adding `imagePullPolicy: Always` to the latest.yml and the latest version yaml. Nightly already has this policy set
> adding always pull to latest yamls

- Makefile
- vultr/cloud.go
Fixed/clean up the error message on the metadata call. Also added `-trimpath` to our builds
n/a
> fix error message + trimpath on builds

- .github/workflows/tagged-releases.yml
- .github/workflows/unit-tests.yml
- README.md
- go.mod
- go.sum
> Go version

- Dockerfile
- Makefile
Have the CCM build in a container during tagged releasse
> CCM Build changes

- vultr/cloud.go
As the title says this will allow anyone using the CCM to adjust the useragent
> Allow changing of UserAgent for govultr

- .github/workflows/tagged-releases.yml
- .github/workflows/unit-tests.yml
- Dockerfile
> updating all go 1.16 references to 1.17

- vultr/cloud.go
- vultr/instancesv2.go
This PR will implement instanceV2 into the CCM and remove functionality of instances
> implemented instancesv2

- vultr/instancesv2.go
This PR will resolve the issues we are seeing with instance lookups, and improve logging.
> Update instanceV2 to fix instance lookup

- vultr/instances.go
- vultr/instancesv2.go
This PR will increase the page size for instance lookups
> added larger page

- vultr/instances.go
- vultr/instancesv2.go
- vultr/loadbalancers.go
This PR will enabled IPv6 support for the CCM
CLOUD-2672
> ipv6 support for vlb

- .github/workflows/go-checks.yaml
- .github/workflows/releaser.yaml
- .github/workflows/unit-tests.yml
- go.mod
- vultr/cloud.go
- vultr/fakeclient.go
- vultr/instances.go
- vultr/loadbalancers.go
> Update go to v1.20

- main.go
- vultr/fakeclient.go
- vultr/loadbalancers.go
- vultr/secrets.go
This PR will allow the CCM to watch and update LB secrets when they are used.
> added secret watcher logic

- vultr/loadbalancers.go
This PR will add a check to verify whether or not an address is IPv6 or IPv4 and add the appropriate type to the request.
> add ipv6 check

- Dockerfile
- docs/releases/v0.11.0.yml
- go.mod
- go.sum
- vendor/github.com/hashicorp/go-retryablehttp/CHANGELOG.md
- vendor/github.com/hashicorp/go-retryablehttp/client.go
- vendor/github.com/vultr/govultr/v3/.golangci.yaml
- vendor/github.com/vultr/govultr/v3/CHANGELOG.md
- vendor/github.com/vultr/govultr/v3/README.md
- vendor/github.com/vultr/govultr/v3/bare_metal_server.go
- vendor/github.com/vultr/govultr/v3/container_registry.go
- vendor/github.com/vultr/govultr/v3/database.go
- vendor/github.com/vultr/govultr/v3/govultr.go
- vendor/github.com/vultr/govultr/v3/instance.go
- vendor/github.com/vultr/govultr/v3/kubernetes.go
- vendor/github.com/vultr/govultr/v3/marketplace.go
- vendor/github.com/vultr/govultr/v3/object_storage.go
- vendor/modules.txt
- vultr/baremetal.go
- vultr/instances.go
- vultr/instancesv2.go
- vultr/zones.go
This PR will add support for BareMetals in Vultr and cut a new release
> Release v0.11.0 #minor

- .github/workflows/notify-pr.yml
- .github/workflows/releaser.yaml
Fix the notification workflow actions after major version update
> Update mattermost notification workflows

- .github/workflows/notify-issue.yaml
- .github/workflows/releaser.yaml
Fix mattermost notifications
#246
> Fix mattermost notifications

- .github/workflows/go-checks.yaml
- .github/workflows/releaser.yaml
- .github/workflows/unit-tests.yml
- .golangci.yml
- .goreleaser.yml
- vultr/cloud.go
- vultr/loadbalancers.go
Updates the github workflows for goreleaser, golangci-lint and tests
> Goreleaser and golangci-lint workflows updates

- vultr/instancesv2.go
This PR will add an additional check for baremetals.
> Add BM Active check

- go.mod
- go.sum
- vendor/github.com/vultr/govultr/v3/CHANGELOG.md
- vendor/github.com/vultr/govultr/v3/account.go
- vendor/github.com/vultr/govultr/v3/billing.go
- vendor/github.com/vultr/govultr/v3/database.go
- vendor/github.com/vultr/govultr/v3/govultr.go
- vendor/github.com/vultr/govultr/v3/load_balancer.go
- vendor/github.com/vultr/govultr/v3/virtual_file_system_storage.go
- vendor/modules.txt
- vultr/fakeclient.go
> Update govultr from v3.11.2 to v3.15.0

- .github/workflows/releaser.yaml
> Update github-tag-actions from v1.36.0 to v1.71.0

- vultr/loadbalancers.go
This PR will change all of the "Update" calls to "Patch" calls for loadbalancers. This will help prevent race conditions from inadvertently removing existing annotations. 
___
Bug fix
___
Replace Kubernetes Update calls with Patch calls
Prevent race conditions when updating service annotations
Remove retry logic for annotation updates
Use atomic JSON patch for annotation removal
___
```mermaid
flowchart LR
Update["Service Update"] --> Conflict["Race Condition"]
Conflict --> DataLoss["Annotation Loss"]
Patch["Service Patch"] --> Atomic["Atomic Operation"]
Atomic --> Safe["No Race Condition"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td> …
> change kubernetes update calls to patch

- vultr/instances.go
- vultr/loadbalancers.go
- Make the IDs used in the log ouput use quoted string formats so that blank IDs are more easily identified
> Make logs quote IDs in output
